Fix 'Uncaught TypeError: undefined is not a function' in 'routing.js.coffee': The .live() method has been deprecated since jQuery 1.7 and has been removed in 1.9.