Fix 'Uncaught TypeError: undefined is not a function' in 'modals.js.coffee': The .live() method has been deprecated since jQuery 1.7 and has been removed in 1.9. We recommend upgrading code to use the .on() method instead.